### ISSUE TITLE
Bindings From External Assemblies

### ISSUE THREAD

**Issue by andresla** [specsolutions/deveroom-feedback#22] opened 2019-04-03 12:18 UTC
Cannot load Steps from External Assemblies.

```
<specFlow>
  <stepAssemblies>
    <stepAssembly assembly="MySharedBindings" />
  </stepAssemblies>
</specFlow>
```

tried using the json config as:
```
{
   "stepAssemblies": {
      "stepAssembly": {
         "@assembly": "MySharedBindings"
      }
   }
}
```

I keep getting the following error:
`Exit code: 4
Message: 
Error: Exception has been thrown by the target of an invocation. -> Value cannot be null.
Parameter name: assemblyString
Exception: System.Reflection.TargetInvocationException->System.ArgumentNullException
StackTrace:
   at System.Reflection.RuntimeAssembly.CreateAssemblyName(String assemblyString, RuntimeAssembly& assemblyFromResolveEvent)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, StackCrawlMark& stackMark, IntPtr pPrivHostBinder)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.Load(String assemblyString)
   at TechTalk.SpecFlow.Infrastructure.BindingAssemblyLoader.Load(String assemblyName) in D:\a\1\s\TechTalk.SpecFlow\Infrastructure\IBindingAssemblyLoader.cs:line 14
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at TechTalk.SpecFlow.TestRunnerManager.GetBindingAssemblies() in D:\a\1\s\TechTalk.SpecFlow\TestRunnerManager.cs:line 88
   at TechTalk.SpecFlow.TestRunnerManager.InitializeBindingRegistry(ITestRunner testRunner) in D:\a\1\s\TechTalk.SpecFlow\TestRunnerManager.cs:line 69
   at TechTalk.SpecFlow.TestRunnerManager.CreateTestRunner(Int32 threadId) in D:\a\1\s\TechTalk.SpecFlow\TestRunnerManager.cs:line 60
   at Deveroom.VisualStudio.SpecFlowConnector.Discovery.V3000.SpecFlowV3000Discoverer.GetBindingRegistry(Assembly testAssembly, String configFilePath) in W:\Deveroom\Deveroom.VisualStudio\Deveroom.VisualStudio.SpecFlowConnector.V2\Discovery\V3000\SpecFlowV3000Discoverer.cs:line 21
   at Deveroom.VisualStudio.SpecFlowConnector.Discovery.BaseDiscoverer.DiscoverInternal(Assembly testAssembly, String testAssemblyPath, String configFilePath) in W:\Deveroom\Deveroom.VisualStudio\Deveroom.VisualStudio.SpecFlowConnector.V2\Discovery\BaseDiscoverer.cs:line 29
   at Deveroom.VisualStudio.SpecFlowConnector.Discovery.BaseDiscoverer.Discover(Assembly testAssembly, String testAssemblyPath, String configFilePath) in W:\Deveroom\Deveroom.VisualStudio\Deveroom.VisualStudio.SpecFlowConnector.V2\Discovery\BaseDiscoverer.cs:line 21
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Deveroom.VisualStudio.SpecFlowConnector.ReflectionExtensions.ReflectionCallMethod[T](Object obj, String methodName, Type[] parameterTypes, Object[] args) in W:\Deveroom\Deveroom.VisualStudio\Deveroom.VisualStudio.SpecFlowConnector.V2\ReflectionExtensions.cs:line 17
   at Deveroom.VisualStudio.SpecFlowConnector.Discovery.ReflectionSpecFlowDiscoverer.Discover(Assembly testAssembly, String testAssemblyPath, String configFilePath) in W:\Deveroom\Deveroom.VisualStudio\Deveroom.VisualStudio.SpecFlowConnector.V2\Discovery\ReflectionSpecFlowDiscoverer.cs:line 25
   at Deveroom.VisualStudio.SpecFlowConnector.Discovery.DiscoveryProcessor.Process() in W:\Deveroom\Deveroom.VisualStudio\Deveroom.VisualStudio.SpecFlowConnector.V2\Discovery\DiscoveryProcessor.cs:line 41
   at Deveroom.VisualStudio.SpecFlowConnector.ConsoleRunner.EntryPoint(String[] args) in W:\Deveroom\Deveroom.VisualStudio\Deveroom.VisualStudio.SpecFlowConnector.V2\ConsoleRunner.cs:line 27`

**Comment by gasparnagy** [comment] 2019-04-04 12:14
@andresla In the .NET Core version of SpecFlow v3, the App.config file cannot be used, you have to use the json file. The proper format of the specflow.json file to add external assemblies is:

```
{
  "stepAssemblies": [
    {
      "assembly": "MySharedBindings"
    }
  ]
}
```

(Don't forget to set the "copy to output folder" for the json config file.)

You can find a working sample attached. I am closing this issue now, if the issue is not resolved with this, please re-open.

[Sample_MyCalculator_NetCore.zip](https://github.com/specsolutions/deveroom-feedback/files/3043345/Sample_MyCalculator_NetCore.zip)

**Closed by gasparnagy** 2019-04-04 12:14 UTC

**Comment by andresla** [comment] 2019-04-04 17:55
Thanks Gaspar for the quick response, that fixed it 👍
