### ISSUE TITLE
Deveroom fails to discover step definitions when App.config does not contain a <specFlow> node

### ISSUE THREAD

**Issue by jrbye** [specsolutions/deveroom-feedback#24] opened 2019-04-05 13:39 UTC
Here is my setup: Specflow 3.0.191 Specflow.tools.MsBuild.Generation 3.0.191 Specflow.NUnit 3.0.191 Visual Studio 2019 Version 16 Deveroom Extension 1.1.1

When I am in a feature file in Visual Studio I am not able to go to the definition of any of my steps. I have tried F12 as well as right clicking on the step and choosing Go To Definition. Neither goes anywhere or pops any kind of error. There is a disconnect that doesn't prohibit the tests from running but does cause the Go To Definition not to work.

I have followed the configuration guide from the Specflow site (https://specflow.org/2019/updating-to-specflow-3/). My tests are running and working. I have deleted the specmap files from the %TEMP% directory and that didn't do anything. I uninstalled/reinstalled the deveroom Visual Studio plugin also which didn't work.

Here is the output from the Deveroom extension:
Info: .ctor: Starting Deveroom...
Info: CreateProjectScope: Initializing project: Automation
Info: OnSettingsInitialized: Project settings initialized
Warning: RecalculateBindingRegistryInternal: Error during binding discovery. 
Command executed:
  C:\Users\me\source\repos\SPFAutomation\Automation\bin\Debug> C:\USERS\me\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_A2619B6D\EXTENSIONS\2BQDHW0H.REG\Connectors\V1\deveroom-specflow-v1.exe discovery C:\Users\me\source\repos\SPFAutomation\Automation\bin\Debug\Automation.dll C:\Users\me\source\repos\SPFAutomation\Automation\App.config
Exit code: 4
Message: 
Error: Exception has been thrown by the target of an invocation. -> Value cannot be null.
Parameter name: node
Exception: System.Reflection.TargetInvocationException->System.ArgumentNullException
StackTrace:
   at System.Xml.XmlNodeReader..ctor(XmlNode node)
   at TechTalk.SpecFlow.Configuration.ConfigurationSectionHandler.CreateFromXml(XmlNode xmlContent)
   at Deveroom.VisualStudio.SpecFlowConnector.Discovery.V3000.CustomConfigurationLoader.Load(SpecFlowConfiguration specFlowConfiguration)
   at TechTalk.SpecFlow.Infrastructure.ContainerBuilder.CreateGlobalContainer(IRuntimeConfigurationProvider configurationProvider)

Server stack trace: 
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Deveroom.VisualStudio.SpecFlowConnector.ReflectionExtensions.ReflectionCallMethod[T](Object obj, String methodName, Type[] parameterTypes, Object[] args)
   at Deveroom.VisualStudio.SpecFlowConnector.ReflectionExtensions.ReflectionCallMethod[T](Object obj, String methodName, Object[] args)
   at Deveroom.VisualStudio.SpecFlowConnector.Discovery.V3000.SpecFlowV3000Discoverer.GetBindingRegistry(Assembly testAssembly, String configFilePath)
   at Deveroom.VisualStudio.SpecFlowConnector.Discovery.BaseDiscoverer.DiscoverInternal(String testAssemblyPath, String configFilePath)
   at Deveroom.VisualStudio.SpecFlowConnector.Discovery.BaseDiscoverer.Discover(String testAssemblyPath, String configFilePath)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Deveroom.VisualStudio.SpecFlowConnector.Discovery.ISpecFlowDiscoverer.Discover(String testAssembly, String configFilePath)
   at Deveroom.VisualStudio.SpecFlowConnector.Discovery.DiscoveryProcessor.Process()
   at Deveroom.VisualStudio.SpecFlowConnector.ConsoleRunner.EntryPoint(String[] args)

**Comment by gasparnagy** [comment] 2019-04-05 15:16
From the error message maybe there is a problem with your App.config file (C:\Users\me\source\repos\SPFAutomation\Automation\App.config). Maybe it does not contain a <specFlow> element? Could you please check if the problem is solved if you add an empty SpecFlow config node? Like 

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="specFlow" type="TechTalk.SpecFlow.Configuration.ConfigurationSectionHandler, TechTalk.SpecFlow" />
  </configSections>
  <specFlow>
  </specFlow>
</configuration>
```

**Comment by jrbye** [comment] 2019-04-05 15:57
That worked! I thought that since we didn't have to specify the Unit Testing framework in the App config I wouldn't need a specflow section in there. I added it as you specified, cleaned and rebuilt the project and it worked.

Thank you very much for your help.

**Comment by gasparnagy** [comment] 2019-04-05 15:59
OK, thx. I mark this as a bug, as Deveroom should be tolerant for this situation, that is otherwise valid for SpecFlow.

**Comment by gasparnagy** [comment] 2019-04-08 13:16
This (Deveroom fails to discover step definitions when App.config does not contain a <specFlow> node) has been fixed and will be included in the next release

**Closed by gasparnagy** 2019-04-08 13:16 UTC
Labels: bug
